 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  covr:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - /shared/sanjayss/covr/train_sample100.json
          storage:
              - covr/annotations/incontext100.json
        val:
          url:
              - /shared/sanjayss/covr/val_sample1000.json
          storage:
              - covr/annotations/val_sample1000.json
        test:
          url:
              - /shared/sanjayss/covr/val_sample1000.json
          storage:
              - covr/annotations/val_sample1000.json
      images:
          storage: covr/images/
